refactor(app, robot-server): build out pipette offset calibration views and wire up to session
Opentrons/opentrons pull request #6473
Opened 2020-09-02 15:31 UTC by b-cooper

# Overview

Create orchestration component and run app plumbing to manage pipette offset calibration in the run
app. Wire up to robot-server side session plumbing. Create generalized calibration components for
panels that are shared across flows. Eventually all calibration user flows will likely import panels
from this shared directory.

Closes #6408, Closes #6421, Closes #6423, Closes #6425, Closes #6428, Closes #6417

# Changelog

- new `app/src/components/PipetteOffsetCalibration` directory and orchestration component to manage flow
- all child components for pipette offset calibration user flow live in a shared (across calibration flows) directory at `app/src/components/CalibrationPanels`. Eventually we can refactor other flows to use these shared panels to reduce maintenance overhead
- add session plumbing for new pipette offset calibration session to the robot-server

# Review requests

- [ ] ensure the flow is hidden behind the enable calibration overhaul app side feature flag.  
- [ ] step through the flow with either pipette, everything should move, but nothing will be saved

# Risk assessment

med, all behind feature flag, but the reach of the PR is broad.

2020-09-02 19:18 UTC, sfoster1 approved these changes
LGTM once some todos are added. We should get the duplicate code removed quickly

2020-09-02 21:32 UTC, ahiuchingau requested changes
Just a couple of changes. Everything else looks really good!

2020-09-02 21:32 UTC, ahiuchingau commented on app/src/components/CalibrationPanels/CompleteConfirmation.js
> +const COMPLETE_HEADER = 'Deck calibration complete'
The header should change based on the session type

2020-09-02 21:32 UTC, ahiuchingau commented on app/src/components/InstrumentSettings/PipetteOffsetCalibrationControl.js
> +        {BUTTON_TEXT}
I think the calibrate offset button should be inactive/not be shown when a pipette is not attached.
<img width="450" alt="Screen Shot 2020-09-02 at 5 17 59 PM" src="https://user-images.githubusercontent.com/20424172/92037913-87c8e000-ed40-11ea-8ba0-bf0c0e625d44.png">

2020-09-04 13:57 UTC, mcous reviewed
Here's my pass at a code review! Didn't have time to do smoke test or anything but I trust y'all have a handle on that.

Most of my comments are housekeeping and for future reference, but I do see a potential race condition in the wizard exit where the exit command and delete session requests are sent almost simultaneously

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/CompleteConfirmation.js
> +    props.deleteSession()
This looks a little racey (hah).

But yeah, shouldn't we wait for the session exit command to finish its stuff before sending a request to delete the resource? If so, that seems like epic logic

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/CompleteConfirmation.js
> +        data-test="continueButton"
Would a semantic `name` or `title` here make sense?

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/DeckSetup.js
> +          margin={`${SPACING_2} 0`}
I think this should work if you just want to set top and bottom:

```suggestion
          marginY={SPACING_2}
```

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/Introduction.js
> +  cursor: pointer;
Is this needed? I thought this was default behavior for anchor links

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/Introduction.js
> +        padding={`${SPACING_3} 0`}
```suggestion
        paddingY={SPACING_3}
```

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/SaveXYPoint.js
> +        textTransform="uppercase"
Might want to use `TEXT_TRANSFORM_UPPERCASE` for consistency

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/SaveXYPoint.js
> +          data-test="saveButton"
Same comment about `name` or `title`

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/SaveZPoint.js
> +        textTransform="uppercase"
`TEXT_TRANSFORM_UPPERCASE`

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/SaveZPoint.js
> +            align-self: center;
I believe `Text` should have an `alignSelf` prop available

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/SaveZPoint.js
> +          data-test="continueButton"
Does `name` or `title` make sense?

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/TipPickUp.js
> +        marginY={SPACING_2}
Same comment about margin from the parent

2020-09-04 13:57 UTC, mcous commented on app/src/components/CalibrationPanels/TipPickUp.js
> +    <>
Is this fragment necessary?

2020-09-04 13:57 UTC, mcous commented on app/src/components/InstrumentSettings/PipetteOffsetCalibrationControl.js
> +        marginTop={SPACING_2}
Should margin come in from the parent?

2020-09-04 13:57 UTC, mcous commented on app/src/components/InstrumentSettings/PipetteOffsetCalibrationControl.js
> +          padding: ${SPACING_2};
Also just discovered the padding props weren't working on the button variants. Immediate fix is in #6483 if you wanna copy that over (depending on how much it annoys you; for me it was "a lot").

Longer term: I'm still not sure how I feel about variant components (`<SecondaryBtn>`) vs variant props (`<Btn variant="secondary">`). Looking at the `FONT_HEADER_DARK` stuff makes me think we probably want to figure that out soon

2020-09-04 13:57 UTC, mcous commented on components/src/styles/typography.js
> +export const FONT_BODY_2_DARK: CSSRules = css`
I like this use of the CSS prop for variants. In terms of continuing JS housekeeping I think I now know of the following ways we can / do create primitive variants:

- Separate components (e.g. `PrimaryBtn`, `SecondaryBtn`)
- Variant prop (we don't do this, but [here is how styled-system does it](https://styled-system.com/variants)
- Style prop bundle spread (which I toyed with but never included in our codebase), e.g:
    ```js
    const FONT_BODY_2_DARK = {
      fontSize: FONT_SIZE_BODY_2,
      fontWeight: FONT_WEIGHT_REGULAR,
      color: C_DARK_GRAY,
    }
    // ...
    <Text {...FONT_BODY_2_DARK}>
    ```
- CSS prop (e.g. `<Text css={FONT_BODY_2_DARK}>`)

It's probably about time for us to figure out which one(s) we like best and be consistent about it. I think the `css` prop has a lot going for it for this job, but I don't hate any of these options.

I also think if we're going to lean on the `css` prop more, we definitely need to take a look at swapping `styled-components` out for `emotion`. In my playing around with emotion, it treats the `css` prop a lot more like a first-class citizen than styled-components and allows for cool cascading behaviors

2020-09-04 14:16 UTC, b-cooper commented on app/src/components/CalibrationPanels/CompleteConfirmation.js
> +    props.deleteSession()
Yeah, that is logic that is worth adding to prevent bugs down the road. I'll throw it in a short term TODO to be addressed by following integration PRs.

2020-09-04 14:25 UTC, b-cooper commented on app/src/components/CalibrationPanels/Introduction.js
> +        marginY={SPACING_2}
I'll keep that in mind as a technique in other components. In this particular case, there aren't dynamic styles right now, so I don't think there'd be any benefit.

2020-09-04 14:51 UTC, b-cooper commented on components/src/styles/typography.js
> +export const FONT_BODY_2_DARK: CSSRules = css`
I'm definitely up for a circle up as the JS guild to hone in on an approach. I'm not particularly wedded to any of the above options.

2020-09-04 15:52 UTC, ahiuchingau approved these changes
lgtm

2020-09-04 15:53 UTC, merged