fix(api): thermocycler hold_time bug
Opentrons/opentrons pull request #6479
Opened 2020-09-03 16:15 UTC by sanni-t

# Overview

Closes #6392 

# Changelog

- Thermocycler driver: modified the rule that checks if `hold_time` has been updated. It now checks if `hold_time` was *probably* updated, based on the closeness of `hold_time` value read to `hold_time` value set.
- Thermocycler HW control: updated `wait_for_hold` to account for the uncertainty introduced by above logic.

# Review requests

- Are there any edge cases you can think of that could break this logic?
- Is there a better way to make this fix? (without changing the firmware preferably)
- The driver tests that raise error are time-consuming since the error is raised after waiting for 5 seconds. Is there a way to minimize this delay? Or is it okay to let it take all that time?

# Risk assessment

High for thermocycler since it touches a core function of the thermocycler

2020-09-03 17:01 UTC, b-cooper reviewed
This seems like an acceptable fix to the bug. 

There is a new side-effect where setting a temperature with a hold time between 0 and 5 has the potential to be off by 4 seconds in the worst case. 

For instance, setting temp to 35°C with a 4 second hold time will result in the api waiting for 9 seconds in the worst case.  This seems unlikely to occur as the TC would probably respond quicker than 5 seconds, and even if it does that is a very small margin of error. It might be worth noting this in documentation somewhere incase those few seconds are worth being aware of when writing a protocol.

2020-09-03 17:18 UTC, sanni-t commented
> This seems like an acceptable fix to the bug.
> 
> There is a new side-effect where setting a temperature with a hold time between 0 and 5 has the potential to be off by 4 seconds in the worst case.
> 
> For instance, setting temp to 35°C with a 4 second hold time will result in the api waiting for 9 seconds in the worst case. This seems unlikely to occur as the TC would probably respond quicker than 5 seconds, and even if it does that is a very small margin of error. It might be worth noting this in documentation somewhere incase those few seconds are worth being aware of when writing a protocol.

Actually, setting 35C with 4 sec hold_time will have the api wait only 4 seconds. The driver will exit set_temperature immediately since 4 seconds lies in the fuzzy time gap. Then the hardware control will implement a 4 second delay.
(Or am I not understanding your case correctly?)

2020-09-03 17:25 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/thermocycler.py
> +                await self.wait_for_hold()  # What does this wait do?
@b-cooper Do you know why we require this hold?

2020-09-03 18:40 UTC, sfoster1 requested changes
Definitely a logic error in there.

It's also kind of gross to me; what this is doing is working around us not having all the events we require for robust operation. What we need is for the thermocycler firmware to tell us when it acknowledged and is executing a command.

2020-09-03 18:40 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/thermocycler.py
> +        if 0 < hold_time <= HOLD_TIME_FUZZY_SECONDS:
This logic looks a bit weird. If `hold_time` is precisely 0 it will fail the check on line 216 and go to the `else` where it will immediately end the `while` loop.

2020-09-03 18:51 UTC, sanni-t commented on api/src/opentrons/hardware_control/modules/thermocycler.py
> +        if 0 < hold_time <= HOLD_TIME_FUZZY_SECONDS:
Not really an error since we don't want to wait when hold_time is 0. But I understand if you mean I should instead make it 
```
if 0 <= hold_time <= HOLD_TIME_FUZZY_SECONDS:
```

2020-09-03 20:57 UTC, sfoster1 commented on api/src/opentrons/hardware_control/modules/thermocycler.py
> +        if 0 < hold_time <= HOLD_TIME_FUZZY_SECONDS:
Yeah it would be good for it to be explicitly caught, or at least documented. As it is it looks like a bug

2020-09-08 15:07 UTC, mcous approved these changes
Reviewed in person, LGTM

2020-09-08 15:12 UTC, amitlissack approved these changes

2020-09-08 15:14 UTC, sfoster1 approved these changes
Looks good to me

2020-09-08 15:16 UTC, merged

2020-09-08 15:17 UTC, b-cooper approved these changes
📦