chore(build): bump required pipenv
Opentrons/opentrons pull request #6484
Opened 2020-09-03 20:31 UTC by sfoster1

It would be really nice to have a modern pipenv, so let's see if it works.

## Testing
- See if you can still `make setup-py` with this version of pipenv
- See if you can change something in a `Pipfile` and then `pipenv update`

2020-09-04 13:43 UTC, amitlissack approved these changes

2020-09-04 18:50 UTC, mcous requested changes
Other than additional Jest module collisions on the JS side, this looks to be working for me on the Python side

2020-09-04 18:50 UTC, mcous commented on jest.config.js
> +  modulePathIgnorePatterns: ['/shared-data/python/.*'],
I'm still getting Jest module collisions. I think ignore list needs to include all our other Python directories as well:

```shell
∙ make test-js
jest \
	--coverage=true \
	--watch=false \
	--updateSnapshot=false \
	--ci=false
jest-haste-map: Haste module naming collision: @opentrons/update-server
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/update-server/otupdate/package.json
    * <rootDir>/update-server/build/lib/otupdate/package.json

jest-haste-map: Haste module naming collision: @opentrons/api-server
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/api/build/lib/opentrons/package.json
    * <rootDir>/api/src/opentrons/package.json
```

2020-09-08 13:06 UTC, sfoster1 commented on jest.config.js
> +  modulePathIgnorePatterns: ['/shared-data/python/.*'],
Will do

2020-09-08 15:10 UTC, mcous approved these changes

2020-09-08 15:27 UTC, ahiuchingau approved these changes
`make setup` and `make test-py` still worked after switching to the new pipenv

2020-09-08 16:21 UTC, b-cooper commented
worked as expected, tests still pass for py dirs ✅

2020-09-08 20:55 UTC, merged