feat(api): add source blowout location option to transfer function (WIP)
Opentrons/opentrons pull request #6670
Opened 2020-10-02 19:14 UTC by shlokamin

**WIP**
# Overview

This WIP PR adds a source blowout location keyword argument to the transfer, consolidate, and distribute functions in `InstrumentContext`

Pairing credit to @IanLondon 

# Review requests
Please review the general strategy we've followed here and pick it apart!

# Risk assessment

Medium

2020-10-05 19:09 UTC, sfoster1 reviewed
>     * [ ]  Since this is a new kwarg that didn't exist, are we OK without an apiLevel bump or should this require an apiLevel bump?

This is the exact type of thing that apiLevel bumps are for. We bump the apiLevel here so that somebody can reliably know what robot software versions this works on.

2020-10-05 19:15 UTC, sfoster1 requested changes
Code and tests look good, but we need some work in the docs.

This can go in api level 2.8. You should 
- Document it in the [advanced commands specific docs](https://github.com/Opentrons/opentrons/blob/edge/api/docs/v2/new_complex_commands.rst)
- Add it to the [versioning table](https://github.com/Opentrons/opentrons/blob/edge/api/docs/v2/versioning.rst)
- Add checks and tests for the checks in the `InstrumentContext` interface that only allow you to specify the new keyword if the api version is at or above 2.8

2020-10-05 19:15 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        blowout_location = kwargs.get('blowout_location')
Sadly we should document this in the docstring

2020-10-05 19:15 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                'source well', 'destination well', 'trash']:
these should be constants defined somewhere, and possibly be defined as `Literals` from `typing_extensions`

2020-10-05 19:15 UTC, sfoster1 commented on api/src/opentrons/protocols/advanced_control/transfers.py
> +    :py:attr:`BlowOutStrategy.DEST`
Document the new `SOURCE` opetion

2020-10-07 20:25 UTC, shlokamin commented on shared-data/python/opentrons_shared_data/protocol/dev_types.py
> +    TRASH = 'trash'
I tried this using `Literal` but for the life of me couldn't figure out how to do string comparisons 😢

2020-10-07 20:47 UTC, sfoster1 requested changes
Looks good but let's stick with just one major version bump :)

2020-10-07 20:47 UTC, sfoster1 commented on api/docs/v2/versioning.rst
> +|     2.9     |          5.0.0              |
Whoa there. This will go in 2.8, 4.0.0. That's the next release

2020-10-07 20:47 UTC, sfoster1 commented on api/docs/v2/versioning.rst
> +Version 2.9
```suggestion
Version 2.8
```

2020-10-07 20:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if blowout_location and self._api_version < APIVersion(2, 9):
```suggestion
        if blowout_location and self._api_version < APIVersion(2, 8):
```

2020-10-07 20:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                ' version below 2.9, current version is {api_version}'
```suggestion
                ' version below 2.8, current version is {api_version}'
```

2020-10-07 20:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if blowout_location and self._api_version < APIVersion(2, 9):
```suggestion
        if blowout_location and self._api_version < APIVersion(2, 8):
```

2020-10-07 20:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                ' version below 2.9, current version is {api_version}'
```suggestion
                ' version below 2.8, current version is {api_version}'
```

2020-10-07 20:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if blowout_location and self._api_version < APIVersion(2, 9):
```suggestion
        if blowout_location and self._api_version < APIVersion(2, 8):
```

2020-10-07 20:47 UTC, sfoster1 commented on api/src/opentrons/protocol_api/instrument_context.py
> +                ' version below 2.9, current version is {api_version}'
```suggestion
                ' version below 2.8, current version is {api_version}'
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    # not supported in versions below 2.9
```suggestion
    # not supported in versions below 2.8
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    context_and_labware = make_context_and_labware(APIVersion(2, 8))
```suggestion
    context_and_labware = make_context_and_labware(APIVersion(2, 7))
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +            'below 2.9, current version is 2.8'):
```suggestion
            'below 2.8, current version is 2.7'):
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    context_and_labware = make_context_and_labware(APIVersion(2, 9))
```suggestion
    context_and_labware = make_context_and_labware(APIVersion(2, 8))
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    context_and_labware = make_context_and_labware(APIVersion(2, 9))
```suggestion
    context_and_labware = make_context_and_labware(APIVersion(2, 8))
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    context_and_labware = make_context_and_labware(APIVersion(2, 9))
```suggestion
    context_and_labware = make_context_and_labware(APIVersion(2, 8))
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    context_and_labware = make_context_and_labware(APIVersion(2, 9))
```suggestion
    context_and_labware = make_context_and_labware(APIVersion(2, 8))
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    context_and_labware = make_context_and_labware(APIVersion(2, 9))
```suggestion
    context_and_labware = make_context_and_labware(APIVersion(2, 8))
```

2020-10-07 20:47 UTC, sfoster1 commented on api/tests/opentrons/protocol_api/test_instrument.py
> +    context_and_labware = make_context_and_labware(APIVersion(2, 9))
```suggestion
    context_and_labware = make_context_and_labware(APIVersion(2, 8))
```

2020-10-07 20:47 UTC, sfoster1 commented on robot-server/tests/integration/test_health_check.tavern.yaml
> +          - 9
```suggestion
          - 8
```

2020-10-07 20:56 UTC, shlokamin commented on api/docs/v2/versioning.rst
> +|     2.9     |          5.0.0              |
lol yes my bad

2020-10-08 20:38 UTC, sfoster1 approved these changes
Code and docs LGTM!

2020-10-09 20:11 UTC, amitlissack commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if kwargs.get('blow_out') and not blowout_location:
Minor point but can we just call `kwargs.get('blow_out')` once?

2020-10-09 20:11 UTC, amitlissack commented on api/tests/opentrons/protocol_api/test_instrument.py
> +def make_context_and_labware():
This is certainly fine, but....

You could consider doing this differently:
one way:
```
@pytest.fixture(params=[(2, 8), (2,7)])
def pctxt(request):
    return ProtocolContext(request.param)
```
This will create create two fixtures for the two versions. You can then use that `pctxt` fixture  in one to create the instrument and labware contexts. 


Another way .... is to use `pytest.mark.parameterize` the various values (version, .error string, etc)

2020-10-12 16:34 UTC, shlokamin commented on api/tests/opentrons/protocol_api/test_instrument.py
> +def make_context_and_labware():
I don't understand this part:

> You can then use that pctxt fixture in one to create the instrument and labware contexts.

It looks like calling `@pytest.fixture` with `params` will create multiple fixtures, so that when you have a test that depends on that fixture function, it will get run multiple times (which should be the length of the `params` list).

But that means that the contents of my test function must still test for the two different scenarios (`params=[(2, 8), (2,7)]`). If the version is `2.8` I want to do one thing, if it is `2.7` I want another. So if I did something like:

```
@pytest.fixture(params=[(2, 8), (2,7)])
def pctxt(request):
    return ProtocolContext(request.param)

def test_blowout_location_unsupported_version(pctx):
     lw = ctx.load_labware('biorad_96_wellplate_200ul_pcr', 1)
     instr = ctx.load_instrument('p300_single', Mount.RIGHT)

     with pytest.raises(
            ValueError,
            match='Cannot specify blowout location when using api version ' +
            'below 2.8, current version is 2.7'):
        instr.transfer(
            100,
            lw1['A1'],
            lw1['A2'],
            blowout_location='foo nonsense')
```

This would work for the `2.7` fixture (since we expect a version error) , but not for the `2.8` fixture.

Using `parms` seems useful if I want to test a bunch of similar scenarios for the same type of assertion. For example, if both `2.7` and `2.8` resulted in the same `ValueError`, this would seem nice. But when assertions differ I'm not sure how to best use it...

`@pytest.mark.parametrize` does seem like it would help though, since I can have control over different sorts of expected values. As you said, I can parametrize versions, error strings, blowout location values, etc.

I'm going to try that, but am I missing something with regards to what I was saying about just using `params`? I'm a noob at unit testing in Python and would like to get better so I appreciate you helping me out!

2020-10-12 16:34 UTC, shlokamin commented on api/src/opentrons/protocol_api/instrument_context.py
> +        blowout_location = kwargs.get('blowout_location')
good call

2020-10-12 16:34 UTC, shlokamin commented on api/src/opentrons/protocol_api/instrument_context.py
> +                'blowout location should be either "source well",' +
cool, makes sense!

2020-10-12 16:35 UTC, shlokamin commented on api/src/opentrons/protocol_api/instrument_context.py
> +        if kwargs.get('blow_out') and not blowout_location:
yep! this actually made me realize that variable names were not named very clearly, so thanks!

2020-10-12 18:06 UTC, shlokamin commented on api/tests/opentrons/protocol_api/test_instrument.py
> +def make_context_and_labware():
Hm... actually, I'm not able to split this up nicely with `@pytest.mark.parametrize` without it turning out awkward and hard to read. @amitlissack would you be down to pair with me on refactoring this test? I'm gonna merge this PR for now since it's been sitting around a while, but would love to put up a new one together to address this!

2020-10-12 19:07 UTC, merged