fix(api,robot-server): upgrade pydantic, upgrade and add test dev deps
Opentrons/opentrons pull request #6673
Opened 2020-10-05 19:15 UTC by mcous

## Overview

This PR is here to solve a few issues in our Python stack, one of which is blocking and the rest of which are just annoying.

Main reason for PR:
- We need (want?) Pydantic available in `api` to move neutral protocol engine stuff into `api` where it can live closer to other protocol-related stuff
    - Upgraded to latest Pydantic for important features around default field values
    - Will require buildroot update: https://github.com/Opentrons/buildroot/issues/107

Additional stuff in PR:
- Upgraded pytest to latest
- Upgraded tavern to latest (current version can hide test that should be failing, see #6665 
- Added `mock` package to get access to the Python 3.7 backport of `AsyncMock`
- Added `pytest-watch` package to have watch mode for `pytest`

Why did I lump a bunch of disparate stuff into one PR? Because every single call to `pipenv install` on my machine takes 2 minutes and most of them require me to `rm -rf Pipfile.lock` to get the commands to actually succeed. I decided to put them all in one PR for my own sanity and because lockfile changes are scary and I don't want to deal with them more than once.

# Changelog

See above.

# Review requests

**WIP, CI not currently passing**

- All tests and checks should still pass locally
- Pydantic upgrade most affects robot-server, so whatever smoke tests you can do are helpful there

# Risk assessment

Medium, in the grand scheme of things. Deep dependency issues are problems that we've run into in the past

2020-10-05 19:21 UTC, sfoster1 requested changes
See comment, need to keep the api (and shared-data, though no changes here require it)'s `setup.py` in sync with the non-dev package dependencies for `pypi` distribution

2020-10-05 19:21 UTC, sfoster1 commented on api/Pipfile
> +pydantic = "==1.6.1"
Need to add this to the install dependencies section of the setup.py for `api` since this means users need to install it for the api package to work on their computers

2020-10-06 21:43 UTC, sfoster1 approved these changes
lgtm!

2020-10-07 12:38 UTC, amitlissack approved these changes

2020-10-07 12:38 UTC, amitlissack commented on api/Pipfile
> +pytest-watch = "~=4.2.0"
Nice!

2020-10-07 13:55 UTC, merged