chore: notify server ci
Opentrons/opentrons pull request #6755
Opened 2020-10-13 18:10 UTC by amitlissack

# Overview

Adding requirements for running CI

closes #6752 

# Changelog

- [ ] Added Makefile. This is the first (i think?) which uses Poetry. 
- [ ] Add `notify-server-lint-test` workflow.
- [ ] Added package.json to project.

# Review requests

See inline questions.

# Risk assessment

None

2020-10-13 18:12 UTC, amitlissack commented on .github/actions/python/setup/action.yaml
> +        pip install poetry
This doesn't seem like the way to do this at all. Should I create a new action `/actions/poetry/setup/action.yaml` or something?

2020-10-13 18:12 UTC, amitlissack commented on .github/workflows/robot-server-lint-test.yaml
> +      - '.github/workflows/robot-server-test-lint.yaml'
This feels like it was a typo

2020-10-13 19:02 UTC, sfoster1 commented on .github/actions/python/setup/action.yaml
> +        pip install poetry
No I think this is the right way to do it, especially since (we at least tell ourselves) we're going to switch everything to poetry

2020-10-13 19:05 UTC, sfoster1 requested changes
Couple little things to change about the workflow but it looks good overall

2020-10-13 19:05 UTC, sfoster1 commented on .github/workflows/notify-server-lint-test.yaml
> +      - '.github/actions/python/**'
this probably also wants a path dep on `notify-server/**`. the `push` event occurs on the git blob you just uploaded, and the `pull_request` happens on a merge generated from that and edge`. so you definitely want both

2020-10-13 19:05 UTC, sfoster1 commented on .github/workflows/notify-server-lint-test.yaml
> +    branches-ignore: # ignore any release-related thing (handled elsewhere)
i think we settled on in fact wanting these to trigger these builds

2020-10-13 19:05 UTC, sfoster1 commented on .github/workflows/notify-server-lint-test.yaml
> +    branches-ignore: # ignore any release-related thing (handled elsewhere)
but be careful, there's weird interactions between branch/ branch-ignore, and tags

2020-10-13 19:05 UTC, sfoster1 commented on .github/workflows/robot-server-lint-test.yaml
> +      - '.github/workflows/robot-server-test-lint.yaml'
yeah the names of these files changed a lot

2020-10-13 19:05 UTC, sfoster1 commented on notify-server/Makefile
> +wheel_file = dist/$(call poetry_python_get_wheelname,notify-server,notify_server,$(BUILD_NUMBER))
this seems like it should live in `python.mk`?

2020-10-13 19:06 UTC, amitlissack commented on .github/actions/python/setup/action.yaml
> +        pip install poetry
Oh goody.

2020-10-13 19:08 UTC, amitlissack commented on notify-server/Makefile
> +wheel_file = dist/$(call poetry_python_get_wheelname,notify-server,notify_server,$(BUILD_NUMBER))
There or `poetry.mk`?  Was thinking that there will be other things that should move outta here.

2020-10-14 17:37 UTC, mcous commented on .github/actions/python/setup/action.yaml
> +        pip install poetry
For reference: how we do it in junk-drawer: https://github.com/Opentrons/junk-drawer/blob/main/.github/workflows/ci.yml

2020-10-14 17:56 UTC, mcous requested changes
A couple little changes but otherwise looking greay

2020-10-14 17:56 UTC, mcous commented on notify-server/Makefile
> +	$(POETRY) update
Should this be `poetry install`? Update will update dependencies and modify the lockfile

2020-10-14 17:56 UTC, mcous commented on notify-server/Makefile
> +	rm -rf  `${POETRY} env info -p`
`$(SHX) rm -rf` to avoid problems for our Windows friends

2020-10-14 18:35 UTC, mcous approved these changes

2020-10-14 18:49 UTC, sfoster1 commented on notify-server/Makefile
> +wheel_file = dist/$(call poetry_python_get_wheelname,notify-server,notify_server,$(BUILD_NUMBER))
`python.mk` for the same reasons as in the workflow file - we want to put everything on poetry eventually

2020-10-14 18:50 UTC, sfoster1 approved these changes
Looks great to me!

2020-10-14 18:54 UTC, merged